services:
    Imper86\SupervisorBundle\Service\ConfigGeneratorInterface:
        class: Imper86\SupervisorBundle\Service\ConfigGenerator
        arguments:
            $config: ~
            $parameterBag: '@parameter_bag'

    Imper86\SupervisorBundle\Service\OperatorInterface:
        class: Imper86\SupervisorBundle\Service\Operator
        arguments:
            $config: ~
            $parameterBag: '@parameter_bag'

    Imper86\SupervisorBundle\Command\SupervisorRebuildCommand:
        arguments:
            $config: ~
            $configGenerator: '@Imper86\SupervisorBundle\Service\ConfigGeneratorInterface'
            $operator: '@Imper86\SupervisorBundle\Service\OperatorInterface'
        tags: ['console.command']

    Imper86\SupervisorBundle\Command\SupervisorControlCommand:
        arguments:
            $config: ~
            $operator: '@Imper86\SupervisorBundle\Service\OperatorInterface'
        tags: ['console.command']

    Imper86\SupervisorBundle\Command\SupervisorCleanDirsCommand:
        arguments:
            $config: ~
            $parameterBag: '@parameter_bag'
        tags: ['console.command']

    Imper86\SupervisorBundle\Command\SupervisorCleanLogsCommand:
        arguments:
            $config: ~
            $parameterBag: '@parameter_bag'
        tags: ['console.command']
